// Code generated by ent, DO NOT EDIT.

package departmentlocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLTE(FieldID, id))
}

// DepartmentID applies equality check predicate on the "DepartmentID" field. It's identical to DepartmentIDEQ.
func DepartmentID(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldDepartmentID, v))
}

// LocationID applies equality check predicate on the "LocationID" field. It's identical to LocationIDEQ.
func LocationID(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldLocationID, v))
}

// EndDate applies equality check predicate on the "EndDate" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldEndDate, v))
}

// StartDate applies equality check predicate on the "StartDate" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldStartDate, v))
}

// DepartmentIDEQ applies the EQ predicate on the "DepartmentID" field.
func DepartmentIDEQ(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "DepartmentID" field.
func DepartmentIDNEQ(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "DepartmentID" field.
func DepartmentIDIn(vs ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "DepartmentID" field.
func DepartmentIDNotIn(vs ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// LocationIDEQ applies the EQ predicate on the "LocationID" field.
func LocationIDEQ(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "LocationID" field.
func LocationIDNEQ(v int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "LocationID" field.
func LocationIDIn(vs ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "LocationID" field.
func LocationIDNotIn(vs ...int) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNotIn(FieldLocationID, vs...))
}

// EndDateEQ applies the EQ predicate on the "EndDate" field.
func EndDateEQ(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "EndDate" field.
func EndDateNEQ(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "EndDate" field.
func EndDateIn(vs ...time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "EndDate" field.
func EndDateNotIn(vs ...time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "EndDate" field.
func EndDateGT(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "EndDate" field.
func EndDateGTE(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "EndDate" field.
func EndDateLT(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "EndDate" field.
func EndDateLTE(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLTE(FieldEndDate, v))
}

// StartDateEQ applies the EQ predicate on the "StartDate" field.
func StartDateEQ(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "StartDate" field.
func StartDateNEQ(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "StartDate" field.
func StartDateIn(vs ...time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "StartDate" field.
func StartDateNotIn(vs ...time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "StartDate" field.
func StartDateGT(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "StartDate" field.
func StartDateGTE(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "StartDate" field.
func StartDateLT(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "StartDate" field.
func StartDateLTE(v time.Time) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(sql.FieldLTE(FieldStartDate, v))
}

// HasAsset applies the HasEdge predicate on the "Asset" edge.
func HasAsset() predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssetWith applies the HasEdge predicate on the "Asset" edge with a given conditions (other predicates).
func HasAssetWith(preds ...predicate.Asset) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AssetInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssetTable, AssetColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromDepartmentLocation applies the HasEdge predicate on the "FromDepartmentLocation" edge.
func HasFromDepartmentLocation() predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromDepartmentLocationTable, FromDepartmentLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromDepartmentLocationWith applies the HasEdge predicate on the "FromDepartmentLocation" edge with a given conditions (other predicates).
func HasFromDepartmentLocationWith(preds ...predicate.AssetTransferLog) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FromDepartmentLocationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FromDepartmentLocationTable, FromDepartmentLocationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToDepartmentLocation applies the HasEdge predicate on the "ToDepartmentLocation" edge.
func HasToDepartmentLocation() predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ToDepartmentLocationTable, ToDepartmentLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToDepartmentLocationWith applies the HasEdge predicate on the "ToDepartmentLocation" edge with a given conditions (other predicates).
func HasToDepartmentLocationWith(preds ...predicate.AssetTransferLog) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ToDepartmentLocationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ToDepartmentLocationTable, ToDepartmentLocationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "Department" edge.
func HasDepartment() predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "Department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "Location" edge.
func HasLocation() predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "Location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Location) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocationInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DepartmentLocation) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DepartmentLocation) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DepartmentLocation) predicate.DepartmentLocation {
	return predicate.DepartmentLocation(func(s *sql.Selector) {
		p(s.Not())
	})
}
