// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// AssetGroup is the predicate function for assetgroup builders.
type AssetGroup func(*sql.Selector)

// AssetPhoto is the predicate function for assetphoto builders.
type AssetPhoto func(*sql.Selector)

// AssetTransferLog is the predicate function for assettransferlog builders.
type AssetTransferLog func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// DepartmentLocation is the predicate function for departmentlocation builders.
type DepartmentLocation func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)
