// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/asset"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/assetgroup"
)

// AssetGroupCreate is the builder for creating a AssetGroup entity.
type AssetGroupCreate struct {
	config
	mutation *AssetGroupMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (agc *AssetGroupCreate) SetName(s string) *AssetGroupCreate {
	agc.mutation.SetName(s)
	return agc
}

// SetID sets the "id" field.
func (agc *AssetGroupCreate) SetID(i int) *AssetGroupCreate {
	agc.mutation.SetID(i)
	return agc
}

// AddAssetIDs adds the "Asset" edge to the Asset entity by IDs.
func (agc *AssetGroupCreate) AddAssetIDs(ids ...int) *AssetGroupCreate {
	agc.mutation.AddAssetIDs(ids...)
	return agc
}

// AddAsset adds the "Asset" edges to the Asset entity.
func (agc *AssetGroupCreate) AddAsset(a ...*Asset) *AssetGroupCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return agc.AddAssetIDs(ids...)
}

// Mutation returns the AssetGroupMutation object of the builder.
func (agc *AssetGroupCreate) Mutation() *AssetGroupMutation {
	return agc.mutation
}

// Save creates the AssetGroup in the database.
func (agc *AssetGroupCreate) Save(ctx context.Context) (*AssetGroup, error) {
	return withHooks[*AssetGroup, AssetGroupMutation](ctx, agc.sqlSave, agc.mutation, agc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (agc *AssetGroupCreate) SaveX(ctx context.Context) *AssetGroup {
	v, err := agc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agc *AssetGroupCreate) Exec(ctx context.Context) error {
	_, err := agc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agc *AssetGroupCreate) ExecX(ctx context.Context) {
	if err := agc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (agc *AssetGroupCreate) check() error {
	if _, ok := agc.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "AssetGroup.Name"`)}
	}
	return nil
}

func (agc *AssetGroupCreate) sqlSave(ctx context.Context) (*AssetGroup, error) {
	if err := agc.check(); err != nil {
		return nil, err
	}
	_node, _spec := agc.createSpec()
	if err := sqlgraph.CreateNode(ctx, agc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	agc.mutation.id = &_node.ID
	agc.mutation.done = true
	return _node, nil
}

func (agc *AssetGroupCreate) createSpec() (*AssetGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetGroup{config: agc.config}
		_spec = sqlgraph.NewCreateSpec(assetgroup.Table, sqlgraph.NewFieldSpec(assetgroup.FieldID, field.TypeInt))
	)
	if id, ok := agc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := agc.mutation.Name(); ok {
		_spec.SetField(assetgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := agc.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assetgroup.AssetTable,
			Columns: []string{assetgroup.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetGroupCreateBulk is the builder for creating many AssetGroup entities in bulk.
type AssetGroupCreateBulk struct {
	config
	builders []*AssetGroupCreate
}

// Save creates the AssetGroup entities in the database.
func (agcb *AssetGroupCreateBulk) Save(ctx context.Context) ([]*AssetGroup, error) {
	specs := make([]*sqlgraph.CreateSpec, len(agcb.builders))
	nodes := make([]*AssetGroup, len(agcb.builders))
	mutators := make([]Mutator, len(agcb.builders))
	for i := range agcb.builders {
		func(i int, root context.Context) {
			builder := agcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, agcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, agcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, agcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (agcb *AssetGroupCreateBulk) SaveX(ctx context.Context) []*AssetGroup {
	v, err := agcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agcb *AssetGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := agcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agcb *AssetGroupCreateBulk) ExecX(ctx context.Context) {
	if err := agcb.Exec(ctx); err != nil {
		panic(err)
	}
}
