// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/assetphoto"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/predicate"
)

// AssetPhotoDelete is the builder for deleting a AssetPhoto entity.
type AssetPhotoDelete struct {
	config
	hooks    []Hook
	mutation *AssetPhotoMutation
}

// Where appends a list predicates to the AssetPhotoDelete builder.
func (apd *AssetPhotoDelete) Where(ps ...predicate.AssetPhoto) *AssetPhotoDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *AssetPhotoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, AssetPhotoMutation](ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *AssetPhotoDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *AssetPhotoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(assetphoto.Table, sqlgraph.NewFieldSpec(assetphoto.FieldID, field.TypeInt))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// AssetPhotoDeleteOne is the builder for deleting a single AssetPhoto entity.
type AssetPhotoDeleteOne struct {
	apd *AssetPhotoDelete
}

// Where appends a list predicates to the AssetPhotoDelete builder.
func (apdo *AssetPhotoDeleteOne) Where(ps ...predicate.AssetPhoto) *AssetPhotoDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *AssetPhotoDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{assetphoto.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *AssetPhotoDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
