// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/asset"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/assettransferlog"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/department"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/departmentlocation"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/location"
	"github.com/qin-guan/WorldSkills/Kazan2019/ent/predicate"
)

// DepartmentLocationQuery is the builder for querying DepartmentLocation entities.
type DepartmentLocationQuery struct {
	config
	ctx                        *QueryContext
	order                      []OrderFunc
	inters                     []Interceptor
	predicates                 []predicate.DepartmentLocation
	withAsset                  *AssetQuery
	withFromDepartmentLocation *AssetTransferLogQuery
	withToDepartmentLocation   *AssetTransferLogQuery
	withDepartment             *DepartmentQuery
	withLocation               *LocationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DepartmentLocationQuery builder.
func (dlq *DepartmentLocationQuery) Where(ps ...predicate.DepartmentLocation) *DepartmentLocationQuery {
	dlq.predicates = append(dlq.predicates, ps...)
	return dlq
}

// Limit the number of records to be returned by this query.
func (dlq *DepartmentLocationQuery) Limit(limit int) *DepartmentLocationQuery {
	dlq.ctx.Limit = &limit
	return dlq
}

// Offset to start from.
func (dlq *DepartmentLocationQuery) Offset(offset int) *DepartmentLocationQuery {
	dlq.ctx.Offset = &offset
	return dlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dlq *DepartmentLocationQuery) Unique(unique bool) *DepartmentLocationQuery {
	dlq.ctx.Unique = &unique
	return dlq
}

// Order specifies how the records should be ordered.
func (dlq *DepartmentLocationQuery) Order(o ...OrderFunc) *DepartmentLocationQuery {
	dlq.order = append(dlq.order, o...)
	return dlq
}

// QueryAsset chains the current query on the "Asset" edge.
func (dlq *DepartmentLocationQuery) QueryAsset() *AssetQuery {
	query := (&AssetClient{config: dlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(departmentlocation.Table, departmentlocation.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, departmentlocation.AssetTable, departmentlocation.AssetColumn),
		)
		fromU = sqlgraph.SetNeighbors(dlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFromDepartmentLocation chains the current query on the "FromDepartmentLocation" edge.
func (dlq *DepartmentLocationQuery) QueryFromDepartmentLocation() *AssetTransferLogQuery {
	query := (&AssetTransferLogClient{config: dlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(departmentlocation.Table, departmentlocation.FieldID, selector),
			sqlgraph.To(assettransferlog.Table, assettransferlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, departmentlocation.FromDepartmentLocationTable, departmentlocation.FromDepartmentLocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(dlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToDepartmentLocation chains the current query on the "ToDepartmentLocation" edge.
func (dlq *DepartmentLocationQuery) QueryToDepartmentLocation() *AssetTransferLogQuery {
	query := (&AssetTransferLogClient{config: dlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(departmentlocation.Table, departmentlocation.FieldID, selector),
			sqlgraph.To(assettransferlog.Table, assettransferlog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, departmentlocation.ToDepartmentLocationTable, departmentlocation.ToDepartmentLocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(dlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartment chains the current query on the "Department" edge.
func (dlq *DepartmentLocationQuery) QueryDepartment() *DepartmentQuery {
	query := (&DepartmentClient{config: dlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(departmentlocation.Table, departmentlocation.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, departmentlocation.DepartmentTable, departmentlocation.DepartmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(dlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocation chains the current query on the "Location" edge.
func (dlq *DepartmentLocationQuery) QueryLocation() *LocationQuery {
	query := (&LocationClient{config: dlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(departmentlocation.Table, departmentlocation.FieldID, selector),
			sqlgraph.To(location.Table, location.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, departmentlocation.LocationTable, departmentlocation.LocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(dlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DepartmentLocation entity from the query.
// Returns a *NotFoundError when no DepartmentLocation was found.
func (dlq *DepartmentLocationQuery) First(ctx context.Context) (*DepartmentLocation, error) {
	nodes, err := dlq.Limit(1).All(setContextOp(ctx, dlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{departmentlocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) FirstX(ctx context.Context) *DepartmentLocation {
	node, err := dlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DepartmentLocation ID from the query.
// Returns a *NotFoundError when no DepartmentLocation ID was found.
func (dlq *DepartmentLocationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dlq.Limit(1).IDs(setContextOp(ctx, dlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{departmentlocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) FirstIDX(ctx context.Context) int {
	id, err := dlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DepartmentLocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DepartmentLocation entity is found.
// Returns a *NotFoundError when no DepartmentLocation entities are found.
func (dlq *DepartmentLocationQuery) Only(ctx context.Context) (*DepartmentLocation, error) {
	nodes, err := dlq.Limit(2).All(setContextOp(ctx, dlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{departmentlocation.Label}
	default:
		return nil, &NotSingularError{departmentlocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) OnlyX(ctx context.Context) *DepartmentLocation {
	node, err := dlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DepartmentLocation ID in the query.
// Returns a *NotSingularError when more than one DepartmentLocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (dlq *DepartmentLocationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dlq.Limit(2).IDs(setContextOp(ctx, dlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{departmentlocation.Label}
	default:
		err = &NotSingularError{departmentlocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) OnlyIDX(ctx context.Context) int {
	id, err := dlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DepartmentLocations.
func (dlq *DepartmentLocationQuery) All(ctx context.Context) ([]*DepartmentLocation, error) {
	ctx = setContextOp(ctx, dlq.ctx, "All")
	if err := dlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DepartmentLocation, *DepartmentLocationQuery]()
	return withInterceptors[[]*DepartmentLocation](ctx, dlq, qr, dlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) AllX(ctx context.Context) []*DepartmentLocation {
	nodes, err := dlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DepartmentLocation IDs.
func (dlq *DepartmentLocationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dlq.ctx.Unique == nil && dlq.path != nil {
		dlq.Unique(true)
	}
	ctx = setContextOp(ctx, dlq.ctx, "IDs")
	if err = dlq.Select(departmentlocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) IDsX(ctx context.Context) []int {
	ids, err := dlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dlq *DepartmentLocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dlq.ctx, "Count")
	if err := dlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dlq, querierCount[*DepartmentLocationQuery](), dlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) CountX(ctx context.Context) int {
	count, err := dlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dlq *DepartmentLocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dlq.ctx, "Exist")
	switch _, err := dlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dlq *DepartmentLocationQuery) ExistX(ctx context.Context) bool {
	exist, err := dlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DepartmentLocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dlq *DepartmentLocationQuery) Clone() *DepartmentLocationQuery {
	if dlq == nil {
		return nil
	}
	return &DepartmentLocationQuery{
		config:                     dlq.config,
		ctx:                        dlq.ctx.Clone(),
		order:                      append([]OrderFunc{}, dlq.order...),
		inters:                     append([]Interceptor{}, dlq.inters...),
		predicates:                 append([]predicate.DepartmentLocation{}, dlq.predicates...),
		withAsset:                  dlq.withAsset.Clone(),
		withFromDepartmentLocation: dlq.withFromDepartmentLocation.Clone(),
		withToDepartmentLocation:   dlq.withToDepartmentLocation.Clone(),
		withDepartment:             dlq.withDepartment.Clone(),
		withLocation:               dlq.withLocation.Clone(),
		// clone intermediate query.
		sql:  dlq.sql.Clone(),
		path: dlq.path,
	}
}

// WithAsset tells the query-builder to eager-load the nodes that are connected to
// the "Asset" edge. The optional arguments are used to configure the query builder of the edge.
func (dlq *DepartmentLocationQuery) WithAsset(opts ...func(*AssetQuery)) *DepartmentLocationQuery {
	query := (&AssetClient{config: dlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dlq.withAsset = query
	return dlq
}

// WithFromDepartmentLocation tells the query-builder to eager-load the nodes that are connected to
// the "FromDepartmentLocation" edge. The optional arguments are used to configure the query builder of the edge.
func (dlq *DepartmentLocationQuery) WithFromDepartmentLocation(opts ...func(*AssetTransferLogQuery)) *DepartmentLocationQuery {
	query := (&AssetTransferLogClient{config: dlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dlq.withFromDepartmentLocation = query
	return dlq
}

// WithToDepartmentLocation tells the query-builder to eager-load the nodes that are connected to
// the "ToDepartmentLocation" edge. The optional arguments are used to configure the query builder of the edge.
func (dlq *DepartmentLocationQuery) WithToDepartmentLocation(opts ...func(*AssetTransferLogQuery)) *DepartmentLocationQuery {
	query := (&AssetTransferLogClient{config: dlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dlq.withToDepartmentLocation = query
	return dlq
}

// WithDepartment tells the query-builder to eager-load the nodes that are connected to
// the "Department" edge. The optional arguments are used to configure the query builder of the edge.
func (dlq *DepartmentLocationQuery) WithDepartment(opts ...func(*DepartmentQuery)) *DepartmentLocationQuery {
	query := (&DepartmentClient{config: dlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dlq.withDepartment = query
	return dlq
}

// WithLocation tells the query-builder to eager-load the nodes that are connected to
// the "Location" edge. The optional arguments are used to configure the query builder of the edge.
func (dlq *DepartmentLocationQuery) WithLocation(opts ...func(*LocationQuery)) *DepartmentLocationQuery {
	query := (&LocationClient{config: dlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dlq.withLocation = query
	return dlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DepartmentID int `json:"DepartmentID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DepartmentLocation.Query().
//		GroupBy(departmentlocation.FieldDepartmentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dlq *DepartmentLocationQuery) GroupBy(field string, fields ...string) *DepartmentLocationGroupBy {
	dlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DepartmentLocationGroupBy{build: dlq}
	grbuild.flds = &dlq.ctx.Fields
	grbuild.label = departmentlocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DepartmentID int `json:"DepartmentID,omitempty"`
//	}
//
//	client.DepartmentLocation.Query().
//		Select(departmentlocation.FieldDepartmentID).
//		Scan(ctx, &v)
func (dlq *DepartmentLocationQuery) Select(fields ...string) *DepartmentLocationSelect {
	dlq.ctx.Fields = append(dlq.ctx.Fields, fields...)
	sbuild := &DepartmentLocationSelect{DepartmentLocationQuery: dlq}
	sbuild.label = departmentlocation.Label
	sbuild.flds, sbuild.scan = &dlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DepartmentLocationSelect configured with the given aggregations.
func (dlq *DepartmentLocationQuery) Aggregate(fns ...AggregateFunc) *DepartmentLocationSelect {
	return dlq.Select().Aggregate(fns...)
}

func (dlq *DepartmentLocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dlq); err != nil {
				return err
			}
		}
	}
	for _, f := range dlq.ctx.Fields {
		if !departmentlocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dlq.path != nil {
		prev, err := dlq.path(ctx)
		if err != nil {
			return err
		}
		dlq.sql = prev
	}
	return nil
}

func (dlq *DepartmentLocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DepartmentLocation, error) {
	var (
		nodes       = []*DepartmentLocation{}
		_spec       = dlq.querySpec()
		loadedTypes = [5]bool{
			dlq.withAsset != nil,
			dlq.withFromDepartmentLocation != nil,
			dlq.withToDepartmentLocation != nil,
			dlq.withDepartment != nil,
			dlq.withLocation != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DepartmentLocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DepartmentLocation{config: dlq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dlq.withAsset; query != nil {
		if err := dlq.loadAsset(ctx, query, nodes,
			func(n *DepartmentLocation) { n.Edges.Asset = []*Asset{} },
			func(n *DepartmentLocation, e *Asset) { n.Edges.Asset = append(n.Edges.Asset, e) }); err != nil {
			return nil, err
		}
	}
	if query := dlq.withFromDepartmentLocation; query != nil {
		if err := dlq.loadFromDepartmentLocation(ctx, query, nodes,
			func(n *DepartmentLocation) { n.Edges.FromDepartmentLocation = []*AssetTransferLog{} },
			func(n *DepartmentLocation, e *AssetTransferLog) {
				n.Edges.FromDepartmentLocation = append(n.Edges.FromDepartmentLocation, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := dlq.withToDepartmentLocation; query != nil {
		if err := dlq.loadToDepartmentLocation(ctx, query, nodes,
			func(n *DepartmentLocation) { n.Edges.ToDepartmentLocation = []*AssetTransferLog{} },
			func(n *DepartmentLocation, e *AssetTransferLog) {
				n.Edges.ToDepartmentLocation = append(n.Edges.ToDepartmentLocation, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := dlq.withDepartment; query != nil {
		if err := dlq.loadDepartment(ctx, query, nodes, nil,
			func(n *DepartmentLocation, e *Department) { n.Edges.Department = e }); err != nil {
			return nil, err
		}
	}
	if query := dlq.withLocation; query != nil {
		if err := dlq.loadLocation(ctx, query, nodes, nil,
			func(n *DepartmentLocation, e *Location) { n.Edges.Location = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dlq *DepartmentLocationQuery) loadAsset(ctx context.Context, query *AssetQuery, nodes []*DepartmentLocation, init func(*DepartmentLocation), assign func(*DepartmentLocation, *Asset)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DepartmentLocation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Asset(func(s *sql.Selector) {
		s.Where(sql.InValues(departmentlocation.AssetColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DepartmentLocationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "DepartmentLocationID" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (dlq *DepartmentLocationQuery) loadFromDepartmentLocation(ctx context.Context, query *AssetTransferLogQuery, nodes []*DepartmentLocation, init func(*DepartmentLocation), assign func(*DepartmentLocation, *AssetTransferLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DepartmentLocation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.AssetTransferLog(func(s *sql.Selector) {
		s.Where(sql.InValues(departmentlocation.FromDepartmentLocationColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FromDepartmentLocationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "FromDepartmentLocationID" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (dlq *DepartmentLocationQuery) loadToDepartmentLocation(ctx context.Context, query *AssetTransferLogQuery, nodes []*DepartmentLocation, init func(*DepartmentLocation), assign func(*DepartmentLocation, *AssetTransferLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DepartmentLocation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.AssetTransferLog(func(s *sql.Selector) {
		s.Where(sql.InValues(departmentlocation.ToDepartmentLocationColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ToDepartmentLocationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ToDepartmentLocationID" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (dlq *DepartmentLocationQuery) loadDepartment(ctx context.Context, query *DepartmentQuery, nodes []*DepartmentLocation, init func(*DepartmentLocation), assign func(*DepartmentLocation, *Department)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DepartmentLocation)
	for i := range nodes {
		fk := nodes[i].DepartmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(department.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "DepartmentID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dlq *DepartmentLocationQuery) loadLocation(ctx context.Context, query *LocationQuery, nodes []*DepartmentLocation, init func(*DepartmentLocation), assign func(*DepartmentLocation, *Location)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DepartmentLocation)
	for i := range nodes {
		fk := nodes[i].LocationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(location.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "LocationID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dlq *DepartmentLocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dlq.querySpec()
	_spec.Node.Columns = dlq.ctx.Fields
	if len(dlq.ctx.Fields) > 0 {
		_spec.Unique = dlq.ctx.Unique != nil && *dlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dlq.driver, _spec)
}

func (dlq *DepartmentLocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(departmentlocation.Table, departmentlocation.Columns, sqlgraph.NewFieldSpec(departmentlocation.FieldID, field.TypeInt))
	_spec.From = dlq.sql
	if unique := dlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dlq.path != nil {
		_spec.Unique = true
	}
	if fields := dlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, departmentlocation.FieldID)
		for i := range fields {
			if fields[i] != departmentlocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dlq *DepartmentLocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dlq.driver.Dialect())
	t1 := builder.Table(departmentlocation.Table)
	columns := dlq.ctx.Fields
	if len(columns) == 0 {
		columns = departmentlocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dlq.sql != nil {
		selector = dlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dlq.ctx.Unique != nil && *dlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dlq.predicates {
		p(selector)
	}
	for _, p := range dlq.order {
		p(selector)
	}
	if offset := dlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DepartmentLocationGroupBy is the group-by builder for DepartmentLocation entities.
type DepartmentLocationGroupBy struct {
	selector
	build *DepartmentLocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dlgb *DepartmentLocationGroupBy) Aggregate(fns ...AggregateFunc) *DepartmentLocationGroupBy {
	dlgb.fns = append(dlgb.fns, fns...)
	return dlgb
}

// Scan applies the selector query and scans the result into the given value.
func (dlgb *DepartmentLocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dlgb.build.ctx, "GroupBy")
	if err := dlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DepartmentLocationQuery, *DepartmentLocationGroupBy](ctx, dlgb.build, dlgb, dlgb.build.inters, v)
}

func (dlgb *DepartmentLocationGroupBy) sqlScan(ctx context.Context, root *DepartmentLocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dlgb.fns))
	for _, fn := range dlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dlgb.flds)+len(dlgb.fns))
		for _, f := range *dlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DepartmentLocationSelect is the builder for selecting fields of DepartmentLocation entities.
type DepartmentLocationSelect struct {
	*DepartmentLocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dls *DepartmentLocationSelect) Aggregate(fns ...AggregateFunc) *DepartmentLocationSelect {
	dls.fns = append(dls.fns, fns...)
	return dls
}

// Scan applies the selector query and scans the result into the given value.
func (dls *DepartmentLocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dls.ctx, "Select")
	if err := dls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DepartmentLocationQuery, *DepartmentLocationSelect](ctx, dls.DepartmentLocationQuery, dls, dls.inters, v)
}

func (dls *DepartmentLocationSelect) sqlScan(ctx context.Context, root *DepartmentLocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dls.fns))
	for _, fn := range dls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
